### ISSUE TITLE
Unable to upload picture

### ISSUE THREAD

**Issue by jbogard** [lostechies/wordpress#46]
Through the WordPress UI, I got this error:

“vtzf3ftsbl3xv1mbl0un-3.png” has failed to upload due to an error
Unable to create directory wp-content/blogs.dir/38/files/2015/02. Is its parent directory writable by the server?

**Comment by jmeridth** [comment]
Changed group owner on /var/www/apps/wordpress from wordpress user to www-data like it should be. @jbogard please try again.

**Comment by jmeridth** [comment]
@jbogard ha! just glad to help. :smile:
