### ISSUE TITLE
Unable to connect/post to wordpress from LiveWriter after https change

### ISSUE THREAD

**Issue by jmeridth** [lostechies/wordpress#47]
![livewritererror](https://cloud.githubusercontent.com/assets/35014/7006550/b0917002-dc47-11e4-9e9e-03da29925497.png)

Currently being experienced by @jbogard and @gnschenker

**Comment by jbogard** [comment]
What's funny is if HTTPS forces me to use the WP interface instead of WLW that was one of my arguments against getting off of WP.

That and the 4.5M page views we had last year and not wanting to break links.

**Comment by jmeridth** [comment]
Jimmy,
Links aren't broken. They all redirect from the tests I've run. Do you have
any example link(s) that are broken?

**Comment by jbogard** [comment]
No I was referring to moving off of WP

**Comment by jmeridth** [comment]
Ah. I'd love that. :)

**Comment by jmeridth** [comment]
This seems to be encoding related.  Changing my password to have no symbols allows me to get my blog list:

```bash
->$ curl -d "<?xml version=\"1.0\"?> <methodCall> <methodName>wp.getUsersBlogs</methodName> <params> <param> <value>[username redacted]</value> </param> <param> <value>[password redacted]</value> </param> </params> </methodCall>" https://www.lostechies.com/jasonmeridth/xmlrpc.php
<?xml version="1.0"?>
<methodResponse>
  <params>
    <param>
      <value>
      <array><data>
  <value><struct>
  <member><name>isAdmin</name><value><boolean>1</boolean></value></member>
  <member><name>url</name><value><string>https://lostechies.com/jasonmeridth/</string></value></member>
  <member><name>blogid</name><value><string>37</string></value></member>
  <member><name>blogName</name><value><string>Jason Meridth&amp;#039;s Blog</string></value></member>
  <member><name>xmlrpc</name><value><string>https://lostechies.com/jasonmeridth/xmlrpc.php</string></value></member>
</struct></value>
</data></array>
      </value>
    </param>
  </params>
</methodResponse>
```

Still working on it.  Seems wp.getPosts still fails though.

**Comment by jmeridth** [comment]
nm, looks like I need to pass my blog id to get the posts.  that worked.  still getting errors through Blogilo though.  Almost there.  Hopefully the fix isn't removing symbols from passwords :frowning:

**Comment by erichexter** [comment]
i traced the code to here. not sure how you are debugging this..
https://github.com/lostechies/wordpress/blob/master/wp-includes/class-wp-xmlrpc-server.php#L3225

**Comment by erichexter** [comment]
also, it looks like livewritter always calls the blogger.getusersblogs and never calls the wp.getusersblogs.

**Comment by jmeridth** [comment]
Was able to connect and post with MarsEdit and no errors.  I put in Name: `Jason Meridth` and URL: `https://lostechies.com/jasonmeridth` and MarsEdit auto detected the following information:

![screen shot 2015-07-18 at 9 16 04 am](https://cloud.githubusercontent.com/assets/35014/8761891/cc2eff28-2d2d-11e5-8ce5-44052a860f31.png)

The xmlrpc.php link and blog ID are the bits it auto detected.  Can someone please try figuring out their blog id and use that xmlrpc.php url and see if LiveWriter doesn't bork?

**Comment by jmeridth** [comment]
Still happening.  Found a Windows box.

Going to try this out: https://mu.wordpress.org/forums/topic/14046

**Comment by erichexter** [comment]
this is so strange. i get a different certificate when i use my blog
subfolder. Which led me down the path that the certificate does not match
the hostname, i wonder if thats screwing something up.

[image: Inline image 1]

[image: Inline image 2]

Eric Hexter

blog | http://Hex.LosTechies.com
info | http://www.linkedin.com/in/erichexter

**Comment by jmeridth** [comment]
Using the new open source version of Windows Live Writer called [OpenLiveWriter](https://github.com/OpenLiveWriter/OpenLiveWriter) @andrewsiemer was able to connect and post to LT on 1/12/16.  Please use OpenLiveWriter if you want to use WLW.
