### ISSUE TITLE
Powered By Rackspace SSL Error

### ISSUE THREAD

**Issue by dahlbyk** [lostechies/wordpress#49]
https://e6b031908a72d151cb58-e811db8ece5abf3fe1b6c8e3c1955f7f.r83.cf1.rackcdn.com/powered-by-rs-40.jpg is blocked with `net::ERR_INSECURE_RESPONSE` due to certificate mismatch.

https://github.com/lostechies/wordpress/blob/374cc1a1b0837edb0fd37047a7e48d60b26042b1/wp-content/themes/lostechies/footer.php#L38

**Comment by jmeridth** [comment]
Removed the image url with the correct [https url](https://2aa08a5fa1056a15479b-e811db8ece5abf3fe1b6c8e3c1955f7f.ssl.cf1.rackcdn.com/powered-by-rs-40.jpg)

:star2: @dahlbyk
