### ISSUE TITLE
Weird footer plugin turned on

### ISSUE THREAD

**Issue by jbogard** [lostechies/wordpress#50]
https://twitter.com/NotMyself/status/755108167780999168

I turned it off. Just a heads up, not sure if anyone cared about this plugin. Or what. But whatever :)

**Comment by jmeridth** [comment]
I'll look into it. Thank you for sharing.

Cheers,
Jason Meridth

**Comment by jbogard** [comment]
Oh I already turned it off, but didn't really know if someone else had
turned it on for some reason

Thanks Jason!

**Comment by jmeridth** [comment]
@jbogard cool.  We'll wait to see who wonders why it was turned off.  :smile:  I'm going to close this ticket.  Thank you for handling it.
